using ERPWebApp.Models.Inventory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace ERPWebApp.Models.Orders;

[Index(nameof(orderKey), IsUnique = false)]
public class Order
{
    [Key]
    public int ERPOrderId { get; set; }

    /// <summary>
    /// Shipstation system generated identifier for the order. This is a read-only field.
    /// </summary>
    [Display(Name = "Order id")]
    public long orderId { get; set; }

    /// <summary>
    /// A user-defined order number used to identify an order.
    /// </summary>
    [Display(Name = "Order Number"), MaxLength(45), Required, Remote("VerifyOrderNumber", "OrderShipping", ErrorMessage = "{0} does not exist.")]
    public string orderNumber { get; set; }

    /// <summary>
    /// A user-provided key that should be unique to each order. Can only be initialized during order creation. If the orderkey isn't specified during creation, a unique value will be generated and assigned to the order.
    /// </summary>
    [Display(Name = "Order Key"), MaxLength(100)]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public string orderKey { get; set; }
    [Display(Name = "Order Date"), DataType(DataType.DateTime)]
    public DateTime orderDate { get; set; }
    /// <summary>
    /// The timestamp the order was created in ShipStation's database. Read-Only.
    /// </summary>
    [DataType(DataType.DateTime)]
    [Display(Name = "Create Date")]
    public DateTime createDate { get; set; }
    /// <summary>
    /// The timestamp the order was modified in ShipStation. modifyDate will equal createDate until a modification is made. Read-Only.
    /// </summary>
    [Display(Name = "Modify Date"), DataType(DataType.DateTime)]
    public DateTime modifyDate { get; set; }
    [Display(Name = "Payment Date"), DataType(DataType.DateTime)]
    public DateTime? paymentDate { get; set; }
    /// <summary>
    /// The date the order is to be shipped before or on. This field is a suggested value generated by the order source/platform/cart and passed to ShipStation. Not all ShipStation integrations support this field and will show null if absent.
    /// </summary>
    [Display(Name = "Ship By Date"), DataType(DataType.DateTime)]
    public DateTime? shipByDate { get; set; }
    /// <summary>
    /// The order's status. Possible values: "awaiting_payment", "awaiting_shipment", "shipped", "on_hold", "cancelled"
    /// </summary>
    [Display(Name = "Order Status")]
    public OrderStatus orderStatus { get; set; }
    /// <summary>
    /// Unique identifier for the customer. Generated by ShipStation the first time the customer record is created. Read-Only
    /// </summary>
    [Display(Name = "Customer Id")]
    public long? customerId { get; set; }
    /// <summary>
    /// Identifier for the customer in the originating system. This is typically a username or email address. This value is required in order to generate a customer profile
    /// </summary>
    [Display(Name = "Customer Username"), MaxLength(100)]
    public string customerUsername { get; set; } = "";
    [Display(Name = "Customer Email"), MaxLength(70)]
    public string customerEmail { get; set; } = "";
    [Display(Name = "Bill To")]
    public OrderShippingInfo billTo { get; set; } = new OrderShippingInfo();
    [Display(Name = "Ship To")]
    public OrderShippingInfo shipTo { get; set; } = new OrderShippingInfo();
    [Display(Name = "Ship From")]
    public OrderShippingInfo shipFrom { get; set; }
    [Display(Name = "Items")]
    public List<OrderItem> items { get; set; }
    [Display(Name = "Order Total"), Column(TypeName = "decimal(18,2)"), DataType(DataType.Currency)]
    public decimal orderTotal { get; set; }
    [Display(Name = "Amount Paid"), Column(TypeName = "decimal(18,2)"), DataType(DataType.Currency)]
    public decimal amountPaid { get; set; }
    [Display(Name = "Tax Amount"), Column(TypeName = "decimal(18,2)"), DataType(DataType.Currency)]
    public decimal taxAmount { get; set; }
    /// <summary>
    /// Shipping amount paid by the customer, if any.
    /// </summary>
    [Display(Name = "Shipping Amount"), Column(TypeName = "decimal(18,2)"), DataType(DataType.Currency)]
    public decimal shippingAmount { get; set; }
    [Display(Name = "Customer Notes"), MaxLength(4000)]
    public string customerNotes { get; set; }
    [Display(Name = "Internal Notes")] //No max length limit
    public string internalNotes { get; set; }
    [Display(Name = "Is Gift")]
    public bool gift { get; set; }
    [Display(Name = "Gift Message"), MaxLength(500)]
    public string giftMessage { get; set; }
    [Display(Name = "Payment Method"), MaxLength(100)]
    public string paymentMethod { get; set; }
    /// <summary>
    /// Identifies the shipping service selected by the customer when placing this order. This value is given to ShipStation by the marketplace/cart. If value is "null" then the marketplace or cart does not support this field in ShipStation.
    /// </summary>
    [Display(Name = "Requested Shipping Service"), MaxLength(50)]
    public string requestedShippingService { get; set; }
    /// <summary>
    /// The code for the carrier that is to be used(or was used) when this order is shipped(was shipped).
    /// </summary>
    [Display(Name = "Carrier Code"), MaxLength(50)]
    public string carrierCode { get; set; }
    [Display(Name = "Carrier Nickname"), MaxLength(50)]
    public string carrierNickname { get; set; }
    /// <summary>
    /// The code for the shipping service that is to be used(or was used) when this order is shipped(was shipped).
    /// </summary>
    [Display(Name = "Service Code"), MaxLength(50)]
    public string serviceCode { get; set; }
    /// <summary>
    /// The code for the package type that is to be used(or was used) when this order is shipped(was shipped).
    /// </summary>
    [Display(Name = "Package Code"), MaxLength(50)]
    public string packageCode { get; set; }
    /// <summary>
    /// The type of delivery confirmation that is to be used(or was used) when this order is shipped(was shipped).
    /// </summary>
    public Confirmation confirmation { get; set; }
    [Display(Name = "Date Shipped"), DataType(DataType.DateTime)]
    public DateTime? shipDate { get; set; }
    [Display(Name = "Hold Until Date"), DataType(DataType.DateTime)]
    public DateTime? holdUntilDate { get; set; }
    /// <summary>
    /// Weight of the order.
    /// </summary>
    public OrderWeight weight { get; set; } = new OrderWeight();
    /// <summary>
    /// Dimensions of the order.
    /// </summary>
    public OrderDimensions dimensions { get; set; } = new OrderDimensions();
    /// <summary>
    /// The shipping insurance information associated with this order.
    /// </summary>
    public OrderInsuranceOptions insuranceOptions { get; set; } = new OrderInsuranceOptions();
    /// <summary>
    /// Customs information that can be used to generate customs documents for international orders.
    /// </summary>
    public OrderInternationalOptions internationalOptions { get; set; } = new OrderInternationalOptions();
    /// <summary>
    /// Various advanced options that may be available depending on the shipping carrier that is used to ship the order.
    /// </summary>
    public OrderAdvancedOptions advancedOptions { get; set; } = new OrderAdvancedOptions();
    /// <summary>
    /// Custom field to better specify the order link for external order APIs 
    /// </summary>
    public List<OrderSource> Sources { get; set; } = [];

    /// <summary>
    /// Each tagId identifies a tag that has been associated with this order. See also Add Tag to Order, List Orders by Tag, Remove Tag from Order, Product Tag, and List Products.
    /// </summary>
    [Display(Name = "Order Tags"), NotMapped]
    public int[] tagIds { get; set; } = [];
    public List<OrderTag> Tags { get; set; } = [];

    /// <summary>
    /// User assigned to Order/Shipment in the GUID. Read-Only.
    /// </summary>
    [Display(Name = "ShipStation User Id")]
    public string userId { get; set; }
    /// <summary>
    /// States whether the order has is current marked as externally fulfilled by the marketplace. A common example is when an Amazon order is marked an Amazon Fulfilled Network (AFN). If the order is an AFN then this element will be true. Read-Only.
    /// </summary>
    [Display(Name = "Externally Fulfilled")]
    public bool externallyFulfilled { get; set; } = true;
    /// <summary>
    /// If externallFulfilled is true then this string will return how the order is being fulfilled by the marketplace. Read-Only.
    /// </summary>
    [MaxLength(50)]
    public string externallyFulfilledBy { get; set; }
    [Display(Name = "Shipments")]
    public List<OrderShipment> orderShipments { get; set; }
    [Display(Name = "Fulfillments")]
    public List<OrderFulfillment> orderFulfillments { get; set; }
    [NotMapped]
    public bool IsCreateShipmentClicked { get; set; }
    [NotMapped]
    public bool IsGetEstimatesClicked { get; set; }
    [Display(Name = "Estimated Shipment Cost"), Column(TypeName = "decimal(18,4)")]
    public decimal estimatedShipmentCost { get; set; }
    [Display(Name = "Is Expedited")]
    public bool isExpedited { get; internal set; }
    [Display(Name = "Carrier Id"), MaxLength(50)]
    public string carrierId { get; internal set; }
    [Timestamp]
    public byte[] ERPTimestamp { get; internal set; }
    [MaxLength(100)]
    public string ERPModifyByUserId { get; internal set; }


    #region Order duplication related properties

    /// <summary>
    /// Reason for this order duplication
    /// </summary>
    [Display(Name = "Duplication Reason")]
    public DuplicationReason? duplicationReason { get; set; }

    /// <summary>
    /// Is this order duplicated
    /// </summary>
    [Display(Name = "Is Order Duplicated")]
    public bool? IsDuplicated { get; set; }

    /// <summary>
    /// Parent order Id of the duplicated order
    /// </summary>
    [Display(Name = "Parent Order Id")]
    public int? ParentERPOrderId { get; set; }
    [ForeignKey("ParentERPOrderId")]
    public virtual Order ParentOrder { get; set; }

    #endregion

    public interface IOrderShippingInformation
    {
        [Display(Name = "Full Name")]
        protected static string name { get; }
        [Display(Name = "Company")]
        protected static string company { get; }
        [Display(Name = "Street Line1")]
        protected static string street1 { get; }
        [Display(Name = "Street Line2")]
        protected static string street2 { get; }
        [Display(Name = "Street Line3")]
        protected static string street3 { get; }
        [Display(Name = "City")]
        protected static string city { get; }
        [Display(Name = "State")]
        protected static string state { get; }
        [Display(Name = "Zip/Postal Code")]
        protected static string postalCode { get; }
        /// <summary>
        /// Country Code. The two-letter ISO Origin Country code is required.
        /// </summary>
        [Display(Name = "Country")]
        protected static string country { get; }
        [Display(Name = "Phone Number")]
        protected static string phone { get; }
        [Display(Name = "Is Residential")]
        protected static bool? residential { get; }
        /// <summary>
        /// Identifies whether the address has been verified by ShipStation (read only). Possible values: Address not yet validated, Address validated successfully, Address validation warning, Address validation failed.
        /// </summary>
        protected AddressVerified addressVerified
        {
            get { return addressVerified; }
            set
            {
                if (Enum.TryParse(value.ToString().Replace(' ', '_'), out AddressVerified result))
                {
                    addressVerified = result;
                }
                else
                    throw new InvalidDataException();
            }
        }

        protected enum AddressVerified
        {
            [Display(Name = "Address not yet validated")]
            Address_not_yet_validated,
            [Display(Name = "Address validated successfully")]
            Address_validated_successfully,
            [Display(Name = "Address validation warning")]
            Address_validation_warning,
            [Display(Name = "Address validation failed")]
            Address_validation_failed

        }
    }
    public class OrderShippingInfo : IOrderShippingInformation
    {
        [Key]
        public int Id { get; init; }
        [Display(Name = "Street 1"), MaxLength(100)]
        public virtual string street1 { get; init; }
        [Display(Name = "Street 2"), MaxLength(100)]
        public virtual string street2 { get; init; }
        [Display(Name = "Street 3"), MaxLength(50)]
        public virtual string street3 { get; init; }
        [Display(Name = "Name"), MaxLength(100)]
        public virtual string name { get; init; }
        [Display(Name = "Phone"), MaxLength(30)]
        [DataType(DataType.PhoneNumber)]
        public virtual string phone { get; init; }
        [Display(Name = "Company"), MaxLength(50)]
        public virtual string company { get; init; }
        [Display(Name = "Postal Code"), MaxLength(10)]
        public virtual string postalCode { get; init; }
        [Display(Name = "City"), MaxLength(50)]
        public virtual string city { get; init; } 
        [Display(Name = "Country"), MaxLength(50)]
        public virtual string country { get; init; }
        [Display(Name = "Is Residential")]
        public virtual bool? residential { get; set; } = true;
        [Display(Name = "State"), MaxLength(50)]
        public virtual string state { get; init; }
    }

    public class OrderWeight
    {
        [Column(TypeName = "decimal(18,4)"), Range(1, double.MaxValue, ErrorMessage = "{0} must be greater or equal to {1}.")]
        public decimal value { get; set; } = 1.00m;
        /// <summary>
        /// units of weight. Allowed units are: "pounds", "ounces", or "grams"
        /// </summary>
        [System.Text.Json.Serialization.JsonConverter(typeof(JsonStringEnumConverter<Units>))]
        public Units units { get; set; } = Units.ounces;
        /// <summary>
        /// (read only) A numeric value that is equivalent to the above units field.
        /// </summary>
        [Display(Name = "Weight Unit")]
        public int WeightUnits { get; set; } = (int)Units.ounces;
        public enum Units
        {
            pounds = 0,
            ounces = 1,
            grams = 2,
        }


    }
    public class OrderDimensions
    {
        [Display(Name = "Length"), Column(TypeName = "decimal(18,4)"), Range(1, double.MaxValue, ErrorMessage = "{0} must be greater or equal to {1}.")]
        public decimal length { get; set; } = 1.00m;

        [Display(Name = "Height"), Column(TypeName = "decimal(18,4)"), Range(1, double.MaxValue, ErrorMessage = "{0} must be greater or equal to {1}.")]
        public decimal height { get; set; } = 1.00m;

        [Display(Name = "Width"), Column(TypeName = "decimal(18,4)"), Range(1, double.MaxValue, ErrorMessage = "{0} must be greater or equal to {1}.")]
        public decimal width { get; set; } = 1.00m;

        /// <summary>
        /// Units of measurement. Allowed units are: "inches", or "centimeters"
        /// </summary>
        [Display(Name = "Dimension Unit")]
        public Units units { get; set; } = Units.inches;

        public enum Units
        {
            inches,
            centimeters
        }
    }
    public class OrderInsuranceOptions
    {
        /// <summary>
        /// Preferred Insurance provider. Available options: "shipsurance", "carrier", or "provider". The "provider" option is used to indicate that a shipment was insured by a third party other than ShipSurance or the carrier. The insurance is handled outside of ShipStation, and will not affect the cost of processing the label.
        /// </summary>
        public Provider? provider { get; set; } = Provider.shipsurance;
        public bool insureShipment { get; set; } = false;
        [Column(TypeName = "decimal(18,4)")]
        public decimal insuredValue { get; set; } = decimal.Zero;

        public enum Provider
        {
            shipsurance,
            carrier,
            provider,
            none
        }
    }
    public class OrderInternationalOptions
    {
        //[Key]
        //public int OrderInternationOptionsId { get; set; }
        /// <summary>
        /// Contents of international shipment. Available options are: "merchandise", "documents", "gift", "returned_goods", or "sample"
        /// </summary>
        public Contents? contents { get; set; } = Contents.merchandise;
        /// <summary>
        /// NOTE: To supply customsItems in the CreateOrder call and have the values not be overwritten by ShipStation, you must set the International Settings > Customs Declarations to "Leave blank (Enter Manually)" in the UI: https://ss.shipstation.com/#/settings/international
        /// </summary>
        public List<CustomsItem> customsItems { get; set; }
        /// <summary>
        /// Non-Delivery option for international shipment. Available options are: "return_to_sender" or "treat_as_abandoned".
        /// <para />
        /// NOTE: If the shipment is created through the Orders/CreateLabelForOrder endpoint and the nonDelivery field is not specified then value defaults based on the International Setting in the UI.If the call is being made to the Shipments/CreateLabel endpoint and the nonDelivery field is not specified then the value will default to "return_to_sender".
        /// </summary>
        public NonDelivery? nonDelivery { get; set; } = NonDelivery.return_to_sender;

        public class CustomsItem
        {

            /// <summary>
            /// Read Only field. When this field is not submitted in the Order/CreateOrder call, it will create a new customs line. If this field is included when submitting an order through Order/CreateOrder, then it will look for the corresponding customs line and update any values.
            /// </summary>
            //[Display(Name = "Customs Item Id")]
            //public string customsItemId { get; set; }

            [Display(Name = "Description"), MaxLength(300)]
            public string description { get; set; }

            [Display(Name = "Quantity")]
            public int quantity { get; set; }

            [Display(Name = "Value"), Column(TypeName = "decimal(18,4)")]
            public decimal value { get; set; }

            [Display(Name = "Harmonized Commodity Code"), MaxLength(150)]
            public string harmonizedTariffCode { get; set; }

            /// <summary>
            /// The two-letter ISO Origin Country code where the item originated
            /// </summary>
            [Display(Name = "Country Of Origin"), MaxLength(2)]
            public string countryOfOrigin { get; set; }
        }

        public enum Contents
        {
            merchandise,
            documents,
            gift,
            returned_goods,
            sample
        }
        public enum NonDelivery
        {
            return_to_sender,
            treat_as_abandoned
        }
    }
    
    public class OrderTag
    {
        [Key]
        public int OrderTagId { get; set; }
        [Display(Name = "Tag Id")]
        public int tagId { get; set; }
        [Display(Name = "Tag Name"), MaxLength(100)]
        public string name { get; set; }
        [Display(Name = "Color"), MaxLength(50)]
        public string color { get; set; }
        public List<Order> Orders { get; set; } = [];

    }

    public enum OrderStatus
    {
        [Display(Name = "Awaiting Payment")]
        awaiting_payment = 0,
        [Display(Name = "Awaiting Shipment")]
        awaiting_shipment = 1,
        [Display(Name = "Shipped")]
        shipped = 2,
        [Display(Name = "On Hold")]
        on_hold = 3,
        [Display(Name = "Cancelled")]
        cancelled = 4,
        [Display(Name = "Processing")]
        processing = 5,
        [Display(Name = "Pending Fulfillment")]
        pending_fulfillment = 6
    }
    public enum Confirmation
    {
        none,
        delivery,
        signature,
        adult_signature,
        /// <summary>
        /// Available for Fedex Only
        /// </summary>
        direct_signature,
    }
    public enum DuplicationReason
    {
        [Display(Name = "Laser Error")]
        laser_error,
        [Display(Name = "Designer Error")]
        designer_error,
        [Display(Name = "Checker Error")]
        checker_error,
        [Display(Name = "Packaging Error")]
        packaging_error,
        [Display(Name = "Operator Error")]
        operator_error,
        [Display(Name = "Lost In Transit")]
        lost_in_transit,
        [Display(Name = "Transit Damage")]
        transit_damage,
        [Display(Name = "Pre-Shipment")]
        pre_shipment,
        [Display(Name = "Customer Complaint")]
        customer_complaint,
        [Display(Name = "Internal Issues")]
        internal_issues,
        [Display(Name = "Defective Item")]
        defective_item,
        [Display(Name = "Test")]
        test,
    }
    public class OrderSource
    {
        [Key]
        public int OrderSourceId { get; set; }
        [Column(TypeName = "nvarchar(50)")]
        public OrderSourceEnum Name { get; set; }
        public List<Order> Orders { get; set; }
    }

    public enum OrderSourceEnum
    {
        custom,
        shopify,
        etsy,
        shipstation,
        orderdesk,
        amazon,
        zazzle,
        smake,
        tiktok,
        skulabs
    }
}
